#!/bin/bash

action()
{
	service=$1
	action=$2

	# if not available, try systemd
	if [ -e /usr/lib/systemd/system/$service.service ]; then
		systemctl $action $service
		return 1
	# if not available, try upstart
        # if not available, try sysvinit
	elif [ -e "/var/run/$service" -o "$action" == "start" -o "$action" == "status" ]; then
                if [ -e /etc/init/$service.conf ]; then
                        $action $service
                elif [ -e /etc/init.d/$service ]; then
                        /etc/init.d/$service $action
		fi
		return 1
        else
		return 0
	fi
}

case $1 in
        start)
	     for i in WAD-Collector WAD-Selector WAD-Processor
	     do
	     	action $i start
	     done
        ;;
        stop)
	     for i in WAD-Collector WAD-Selector WAD-Processor
	     do
	     	if action $i stop
		then
                	echo "Warning: $i service was not running."
		fi
	     done
        ;;
        restart)
	     for i in WAD-Collector WAD-Selector WAD-Processor
	     do
	     	if action $i restart
		then
			echo "Warning: $i service is not running; starting now."
	                start $i
		fi
	     done
        ;;
        status)
             for i in WAD-Collector WAD-Selector WAD-Processor
             do
                action $i status
             done
        ;;
        *)
             echo "Usage: `basename $0` {start|stop|restart|status}"
        ;;
esac
